[workspace]
members = [".", "demos/*"]

[workspace.dependencies]
undoredo = { version = "0.13", features = ["derive", "rstar", "stable-vec"] }

[package]
name = "polygon_unionfind"
version = "0.9.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Disjoint-set data structure (union-find) for polygons."
repository = "https://github.com/mikwielgus/polygon_unionfind"
documentation = "https://docs.rs/polygon_unionfind"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["geometry", "unionfind"]
categories = ["algorithms", "data-structures", "graphics", "mathematics"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]

## Disable for `no_std` compatibility.
std = []

## Enables integration with [`undoredo`](https://crates.io/crates/undoredo) for
## Undo/Redo functionality.
undoredo = ["dep:undoredo"]

[dependencies]
document-features = { version = "0.2", optional = true }
i_overlay = "4.4"
maplike = { version = "0.13", features = ["stable-vec"] }
num-traits = "0.2"
rstar = "0.12"
rstared = "0.13"
stable-vec = "0.4.2"
undoredo = { workspace = true, optional = true }

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
